### ISSUE TITLE
Draft 0.3 Link seems to be broken

### ISSUE THREAD

**Issue by bit-jniestroj** [decentralized-identity/didwebvh#156]
I just noticed that the link under "Previous Drafts" to the version 0.3 seems to not longer work. It points to this URL https://identity.foundation/didwebvh/next/v0.3 which is not existing.

It's only a small issue but forces you to read the raw markdown if you want to check the spec of the 0.3 version.

**Comment by martipos** [comment]
TNX for the information. Try this link [https://identity.foundation/didwebvh/v0.3/](https://identity.foundation/didwebvh/v0.3/)

**Comment by swcurran** [comment]
Thanks for the issue -- should be fixed by #157 once it is merged.

**Comment by swcurran** [comment]
And, I seemed to have made it worse.  Try #2.  It worked locally...honest!  :-(
